NAME = "aio dio bugs"
AUTHOR = "Rafal Wijata <wijata@nec-labs.com>"
TEST_TYPE = "client"
TEST_CLASS = "Kernel"
TEST_CATEGORY = "Functional"
TIME = "MEDIUM"
DOC = """\
This was originally submitted to
 http://bugzilla.kernel.org/show_bug.cgi?id=6831 by 
Rafal Wijata <wijata@nec-labs.com>.  It caught a race in dio aio completion
that would call aio_complete() before the dio callers would update i_size.
A stat after io_getevents() would not see the new file size.

The bug was fixed in the fs/direct-io.c completion reworking that appeared
in 2.6.20.  This test should fail on 2.6.19.
"""

# tests is a simple array of "cmd" "arguments"
tests = [["aio-dio-invalidate-failure", "poo"],
         ["aio-dio-subblock-eof-read", "eoftest"],
         ["aio-free-ring-with-bogus-nr-pages", ""],
         ["aio-io-setup-with-nonwritable-context-pointer", ""],
         ["aio-dio-extend-stat", "file"],
         ["aio-cve-2016-10044", ""],
         ]
name = 0
arglist = 1


for test in tests:
    results = job.run_test('aio_dio_bugs', test_name=test[name], tag=test[name], args=test[arglist])
